#+TITLE: dwm - dynamic window manager


* What is dwm
=dwm= is an extremely fast, small, and dynamic window manager for X.

** Requirements
In order to build =dwm= you need the =Xlib= header files.


** Installation
Edit =config.mk= to match your local setup =(dwm= is installed into the =/usr/local= namespace by default).

Afterwards enter the following command to build and install =dwm= (if necessary as root):

#+begin_src sh
    make clean install
#+end_src


** Running dwm
Add the following line to your =.xinitrc= to start =dwm= using =startx:=

#+begin_src sh
    exec dwm
#+end_src

In order to connect =dwm= to a specific display, make sure that the =DISPLAY= environment variable is set correctly, e.g.:

#+begin_src sh
    DISPLAY=foo.bar:1 exec dwm
#+end_src

(This will start =dwm= on display :1 of the host =foo.bar=.)

In order to display status info in the bar, you can do something like this in your =.xinitrc=:

#+begin_src sh
    while xsetroot -name "`date` `uptime | sed 's/.*,//'`"
    do
    	sleep 1
    done &
    exec dwm
#+end_src


** Configuration
The configuration of =dwm= is done by creating a custom =config.h= and (re)compiling the source code.

* About my build

** Features
My build of =dwm= is patched to include some nice features:
- clickable status bar using =dwmblocks= and the =statuscmd= patch (I forked Luke Smith's =dwmblocks= build).
- sticky windows.
- vacant tags are hidden, but the little boxes are still displayed.
- multiple scratchpads (a terminal emulator and a terminal-based file manager).
- =shiftview= but patched to only shift to occupied tags (copied from Luke Smith).
- keybinding to restart =dwm= using the =restartsig= patch.
- gaps with granular control using the vanitygaps patch.
- adjustable bar height using the bar height patch.
- possibility to cycle between layouts using the cyclelayout patch.
- new windows spawn right after the currently focused window in the stack using the attachbelow patch.
- advanced stack control using the stacker patch.

** Missing features
The current build satisfies all my needs, but there are certain nice to have features that caught mu eye, which I'll be patching in when I find the time:
- [ ] colours in the status bar.
- [ ] a single tag-set shared between all my monitors (similar behaviour to qtile and spectrwm, which were my intro to tiling window managers) using the single-tagset patch
- [ ] a different colour for the border of floating windows using float-border-color.
- [ ] spawn rules for windows, and the ability to switch to tags with newly spawn windows using the switchtotag patch.
- [ ] the ability to jump to urgent windows using focusurgent patch. It would also be nice to have a different foreground colour for tags with urgent windows.
